# Generated by Django 5.2.17 on 2026-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('code', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'ordering': ('-created_at',),
            },
        ),
    ]
